export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_ARCHIVED: 'ACCOUNT_ARCHIVED',
  LOGIN_BLOCKED: 'LOGIN_BLOCKED',
  RATE_LIMITED: 'RATE_LIMITED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  INTERNAL: 'INTERNAL_ERROR',
  INVALID_OPERATION: 'INVALID_OPERATION',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
  SAME_PASSWORD: 'SAME_PASSWORD',
  CANNOT_MODIFY_OWN_ROLE: 'CANNOT_MODIFY_OWN_ROLE',
  CANNOT_MANAGE_TARGET: 'CANNOT_MANAGE_TARGET',
  CANNOT_ARCHIVE_SELF: 'CANNOT_ARCHIVE_SELF',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
